### ISSUE TITLE
Exception raised by CBDetail when opening a TroncQueteur 

### ISSUE THREAD

**Issue by dev-mansonthomas** [dev-mansonthomas/RedCrossQuest#165]
"exception": {
           "message": "Argument 1 passed to RedCrossQuestDBServiceCreditCardDBService::getCreditCardEntriesForTroncQueteur() must be of the type int, null given, called in /workspace/src/DBService/TroncQueteurDBService.php on line 94",
           "stackTrace": "
#0 /workspace/src/DBService/TroncQueteurDBService.php(94): RedCrossQuestDBServiceCreditCardDBService->getCreditCardEntriesForTroncQueteur(NULL, 190)
#1 /workspace/src/BusinessService/TroncQueteurBusinessService.php(64): RedCrossQuestDBServiceTroncQueteurDBService->getLastTroncQueteurByTroncId(4346, 190)
#2 /workspace/src/routes/routesActions/troncsQueteurs/GetLastTroncQueteurFromTroncId.php(55): RedCrossQuestBusinessServiceTroncQueteurBusinessService->getLastTroncQueteurFromTroncId(4346, 190, 4)

**Comment by dev-mansonthomas** [comment]
Note reproduced while connected as a Nantes user and opening the tronc mentionned with the id 4346
